#cloud-config

hostname: "${hostname}"

users:
  - name: "${user}"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash                 
    ssh-authorized-keys:
      - ${ssh_authorized_keys}

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

# Install helm
package_update: true
packages:
  - qemu-guest-agent # If using bridge network, this package is required

runcmd:
  - sleep 10  # Delay to ensure system is fully initialized
  - systemctl enable --now qemu-guest-agent # If using bridge network, this service should be running