#cloud-config
hostname: "${hostname}"
fqdn: "${hostname}.${domain}"
domain: "${domain}"

# Set up disk partitioning and formatting
# Create the mount point /mnt/data
disk_setup:
  /dev/vdb:
    table: gpt
    layout: true
    overwrite: true
    partitions:
      - size: 100%
        name: "data"
        type: "ext4"
fs_setup:
  - device: /dev/vdb1
    filesystem: ext4
    label: data
mounts:
  - ["/dev/vdb1", "/mnt/data", "ext4", "defaults", "0", "2"]

write_files:
  - path: /etc/hostname
    content: |
      ${hostname}

  - path: /etc/hosts
    content: |
      127.0.0.1   localhost
      127.0.1.1   ${hostname}.${domain} ${hostname}

users:
  - name: "${user}"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash                 
    ssh-authorized-keys:
      - ${ssh_authorized_keys}

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

# Install helm
package_update: true
packages:
  - qemu-guest-agent # If using bridge network, this package is required

runcmd:
  - systemctl enable --now qemu-guest-agent # If using bridge network, this service is required