#cloud-config

hostname: "${hostname}"

users:
  - name: "${user}"
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash                 
    ssh-authorized-keys:
      - ${ssh_authorized_keys}

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

# Install helm
package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

runcmd:
  - curl https://baltocdn.com/helm/signing.asc | apt-key add -
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
  - apt-get update
  - apt-get install -y helm