---
- name: Check if kubeadm is installed
  command: kubeadm version
  register: kubeadm_installed
  ignore_errors: yes  # Continue even if the command fails

- name: Check if kubelet is installed
  command: kubelet --version
  register: kubelet_installed
  ignore_errors: yes

- name: Check if kubectl is installed
  command: kubectl version --client
  register: kubectl_installed

- name: Install kubeadm kubelet kubectl components
  block:
  - name: Download Kubernetes GPG key
    get_url:
      url: "{{ k8s_repo_uri }}/core:/stable:/v{{ k8s_version | regex_replace('\\.\\d+$', '') }}/deb/Release.key"
      dest: /tmp/k8s.gpg
      mode: '0644'
    register: download_result
    retries: 10
    delay: 5
    until: download_result is succeeded

  - name: Convert GPG key to dearmor format
    command: >
      gpg --yes --dearmor -o /usr/share/keyrings/k8s.gpg /tmp/k8s.gpg

  - name: Remove temporary GPG key file
    file:
      path: /tmp/k8s.gpg
      state: absent

  - name: Add Kubernetes repository
    lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: "deb [arch=amd64 signed-by=/usr/share/keyrings/k8s.gpg] {{ k8s_repo_uri }}/core:/stable:/v{{ k8s_version | regex_replace('\\.\\d+$', '') }}/deb/ /"
      create: yes

  - name: Install Kubernetes components
    apt:
      name:
        - kubelet={{  k8s_version  }}*
        - kubeadm={{  k8s_version  }}*
        - kubectl={{  k8s_version  }}*
      state: present
      update_cache: yes

  - name: Mark Kubernetes packages on hold
    command: apt-mark hold {{ item }}
    loop:
      - kubelet
      - kubeadm
      - kubectl
  when: (kubeadm_installed.rc != 0) or (kubelet_installed.rc != 0) or (kubectl_installed.rc != 0)
  
