---

- name: Check if Docker is already installed
  shell: docker info > /dev/null 2>&1
  register: docker_installed
  ignore_errors: yes
  changed_when: false

- name: Install docker if not installed
  block:
  - name: Download Docker installation script
    get_url:
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      mode: '0755'
    register: download_rc
    retries: 10
    delay: 5
    until: download_rc is succeeded

  - name: Install specific version of Docker
    shell: |
      DOCKER_VERSION={{ docker_version }} sh /tmp/get-docker.sh {% if docker_mirror | default('') != '' %}--mirror {{ docker_mirror }}{% endif %}
    args:
      executable: /bin/bash
    retries: 5
    delay: 10
    register: result
    until: result.rc == 0

  - name: Create or update docker service proxy configuration file
    copy:
      dest: /etc/systemd/system/docker.service.d/10-proxy.conf
      content: |
        [Service]
        Environment="HTTP_PROXY={{ http_proxy }}"
        Environment="HTTPS_PROXY={{ https_proxy }}"
        Environment="NO_PROXY={{ no_proxy | default('localhost,127.0.0.1,::1') }},{{ groups['k8s_all'] | map('extract', hostvars, ['inventory_hostname']) | join(',') }},{{ k8s_cidr }},{{ k8s_service_cidr }}"
      mode: '0644'
    when:
      - http_proxy | default('') != ''
      - https_proxy | default('') != ''

  - name: Start and enable Docker
    systemd:
      name: docker
      state: started
      daemon_reload: true
      enabled: yes

  - name: Add user to Docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  when: docker_installed.rc != 0



