---

- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  register: download_rc
  retries: 10
  delay: 5
  until: download_rc is succeeded

- name: Install specific version of Docker
  shell: |
    DOCKER_VERSION={{ docker_version }} sh /tmp/get-docker.sh
  args:
    executable: /bin/bash

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes



