- name: Check if any apt process is running
  shell: pgrep -x apt || pgrep -x apt-get || true
  register: apt_process
  ignore_errors: true

- name: Wait for apt processes to finish if they are running
  wait_for:
    path: /proc/{{ item }}
    state: absent
    timeout: 120
    delay: 5
  loop: "{{ apt_process.stdout.splitlines() }}"
  when: apt_process.stdout != ''

- name: Remove stale apt lock files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend
  when: apt_process.stdout != ''

- name: Run apt-get update
  apt:
    update_cache: yes
  retries: 5
  delay: 10
  until: result is success
  register: result