
- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Wait for all pods to be ready
  become: false
  command: kubectl wait --for=condition=ready pod --all -n kube-system --timeout=300s
  ignore_errors: yes
  when: inventory_hostname in groups['k8s_master'] 