- name: Download Flannel YAML
  get_url:
    url: "https://github.com/flannel-io/flannel/releases/download/v{{ k8s_flannel_version }}/kube-flannel.yml"
    dest: "/tmp/kube-flannel.yml"
    force: yes
  register: download_rc
  retries: 10
  delay: 5
  until: download_rc is succeeded

- name: Update Flannel network CIDR in kube-flannel.yaml
  replace:
    path: "/tmp/kube-flannel.yml"
    regexp: '"Network": "(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2})"'
    replace: '"Network": "{{ k8s_cidr }}"'
    
- name: Apply Flannel YAML
  command: >
    kubectl apply -f /tmp/kube-flannel.yml
- name: Remove Flannel YAML
  file:
    path: "/tmp/kube-flannel.yml"
    state: absent
