---
- hosts: k8s_all
  become: true
  vars_files:
    - vars.yml
  roles:
    - name: preinstall
      when: not k8s_reset | bool
    
    - name: install_docker
      when: not k8s_reset | bool

    - name: config_containerd
      when: not k8s_reset | bool

    - name: install_k8s
      when: not k8s_reset | bool
    
    - reset

- hosts: k8s_master
  become: true
  vars_files:
    - vars.yml
  roles:
    - master_init
    - install_cni

- hosts: k8s_all
  become: true
  vars_files:
    - vars.yml
  roles:
    - worker_join
    - postinstall
