---
- hosts: k8s_all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Check if Kubernetes cluster is ready
      command: kubectl get pods -A
      register: k8s_ready
      ignore_errors: yes
      when: (not k8s_reset | bool) and inventory_hostname in groups['k8s_master']

    - name: Fail and stop the playbook since Kubernetes cluster is ready
      fail:
        msg: "Kubernetes cluster is already ready, skip to install."
      when: (not k8s_reset | bool) and (k8s_ready.rc == 0)
  roles:
    - name: reset
      when: k8s_reset | bool

    - name: preinstall
      when: not k8s_reset | bool
    
    - name: install_containerd
      when: not k8s_reset | bool

    - name: install_k8s
      when: not k8s_reset | bool
    
    - name: master_init
      when: inventory_hostname in groups['k8s_master']

    - name: install_cni
      when: inventory_hostname in groups['k8s_master']

    - name: worker_join

    - name: postinstall
