---
- name: Reset Kubernetes cluster
  command: kubeadm reset -f
  ignore_errors: yes

- name: Delete cni0 bridge
  command: ip link delete cni0
  ignore_errors: yes

- name: Remove /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Set a fact for users
  set_fact:
    users_to_remove:
      - root
      - "{{ ansible_user }}"

- name: Remove Kubernetes config
  file:
    path: "{{ (item == 'root' and '/root' or '/home/' + item) }}/.kube"
    state: absent
  loop: "{{ users_to_remove }}"
