---
- name: Reset Kubernetes cluster
  command: kubeadm reset -f
  ignore_errors: yes

- name: Delete cni0 bridge
  command: ip link delete cni0
  ignore_errors: yes

- name: Remove /etc/cni/net.d directory
  file:
    path: /etc/cni/net.d
    state: absent

- name: Remove Kubernetes config
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: absent