---
- name: Get kubeadm join command
  command: >
    kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname in groups['k8s_master']

- set_fact:
    kubeadm_join_command: "{{ join_command.stdout }}"
  when: inventory_hostname in groups['k8s_master']

- name: Join worker to the master
  command: >
    "{{ hostvars[groups['k8s_master'][0]].kubeadm_join_command }}"
  when: inventory_hostname in groups['k8s_workers']

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Wait for all pods to be ready
  command: >
    kubectl wait --for=condition=ready pod --all --all-namespaces
  register: pod_status
  retries: 30
  delay: 10
  until: pod_status.rc == 0
  when: inventory_hostname in groups['k8s_master']
