- name: Ensure containerd configuration directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate containerd default configuration
  command: containerd config default
  register: containerd_config

- name: Write containerd configuration to file
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Enable SystemdCgroup in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^ *SystemdCgroup *= *false'
    line: 'SystemdCgroup = true'
    backrefs: yes

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted