- name: Install metric server
  include_role:
    name: install_metric_server
  when: k8s_metric_server_enabled and inventory_hostname in groups['k8s_master']

- name: Install helm
  include_role:
    name: install_helm
  when: inventory_hostname in groups['k8s_master']

- name: Install storage provisioner
  include_role:
    name: install_storage_provisioner
  when: k8s_storage_provisioner_enabled